# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Greeting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eGreeting.proto\x12\x08greeting\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t\"6\n\x0b\x46ileRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0b\n\x03\x65xt\x18\x03 \x01(\t\")\n\x0c\x46ileResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t2\x8b\x01\n\x0fGreetingService\x12;\n\x08SayHello\x12\x16.greeting.HelloRequest\x1a\x17.greeting.HelloResponse\x12;\n\nUploadFile\x12\x15.greeting.FileRequest\x1a\x16.greeting.FileResponseBI\n\x1c com.bikash.grpcdemo.serviceB\rGreetingProtoP\x01Z\x18\x62ikash/grpcimpl/greetingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Greeting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034 com.bikash.grpcdemo.serviceB\rGreetingProtoP\001Z\030bikash/grpcimpl/greeting'
  _HELLOREQUEST._serialized_start=28
  _HELLOREQUEST._serialized_end=56
  _HELLORESPONSE._serialized_start=58
  _HELLORESPONSE._serialized_end=91
  _FILEREQUEST._serialized_start=93
  _FILEREQUEST._serialized_end=147
  _FILERESPONSE._serialized_start=149
  _FILERESPONSE._serialized_end=190
  _GREETINGSERVICE._serialized_start=193
  _GREETINGSERVICE._serialized_end=332
# @@protoc_insertion_point(module_scope)
